name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    secrets: inherit
  manifests-check:
    uses: ./.github/workflows/manifests.check.yaml
    secrets: inherit
  image-build-push:
    needs: [lint, manifests-check]
    uses: ./.github/workflows/image-build-push.yaml
    with:
      registry: harbor.k8s.rebellions.in
      image_repository: ${{ vars.IMAGE_REPOSITORY }}
      image_tag: ${{ github.sha }}
    secrets:
      registry_id: ${{ secrets.HARBOR_USERNAME }}
      registry_password: ${{ secrets.HARBOR_PASSWORD }}
